kind = "web"
previewPath = "/"
title = "Lumora"
version = "1.0.0"
id = "artifacts/lumora"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21587

[services.development]
run = "pnpm --filter @workspace/lumora run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lumora", "run", "build" ]
publicDir = "artifacts/lumora/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21587"
BASE_PATH = "/"
